package dev.kof.runtime;

import org.graalvm.polyglot.Value;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * kof.orm no host GraalJS (ORM001) — mesma semântica do runtime JVM gerado por
 * {@code JvmOrmRuntime.source()}: o schema chega PRÉ-SERIALIZADO pelo compilador
 * ({@code name:type:constraints,...}), o SQL é montado no host com o MESMO texto
 * (paridade por construção, como o DB001 fez com o JDBC). Reusa as conexões do
 * {@link KofJsDbBridge} (mesmo registry/DriverManager/classpath do runner).
 *
 * <p>Sem MongoDB no JS: o host só conecta via {@code DriverManager} (SQL), então
 * os ramos mongo do JVM são inalcançáveis aqui (a conexão mongo falharia antes,
 * no DB001). Linhas voltam como JSON strings (contrato {@code List<String>} do
 * untyped); o guest faz o bind de record no MESMO {@code __kof_decode_<T>} que o
 * DB002 ({@code db.query<T>}) usa — nunca {@code Class.forName} no host (Target.JS
 * não emite bytecode). O objeto de {@code save} chega como {@link Value} (o
 * {@code toJSON()} sintético do record) e é lido campo-a-campo pela ordem do schema.
 */
public final class KofJsOrmBridge {

    private KofJsOrmBridge() {
    }

    private record OrmField(String name, String type, boolean generated, boolean unique) {
    }

    private static List<OrmField> schema(String schema) {
        List<OrmField> out = new ArrayList<>();
        for (String part : schema.split(",")) {
            String[] bits = part.split(":");
            boolean generated = false;
            boolean unique = false;
            for (int i = 2; i < bits.length; i++) {
                if ("generated".equals(bits[i])) generated = true;
                if ("unique".equals(bits[i])) unique = true;
            }
            out.add(new OrmField(bits[0], bits.length > 1 ? bits[1] : "string", generated, unique));
        }
        return out;
    }

    private static String dialect(String id) throws Exception {
        String product = KofJsDbBridge.conn(id).getMetaData().getDatabaseProductName().toLowerCase();
        if (product.contains("mysql") || product.contains("mariadb")) return "mysql";
        if (product.contains("postgresql")) return "postgres";
        if (product.contains("oracle")) return "oracle";
        if (product.contains("sqlite")) return "sqlite";
        return "standard";
    }

    private static String sqlType(String type, String dialect) {
        return switch (type) {
            case "int" -> "sqlite".equals(dialect) ? "INTEGER" : "INT";
            case "long" -> "sqlite".equals(dialect) ? "INTEGER" : "BIGINT";
            case "bool" -> "mysql".equals(dialect) ? "TINYINT(1)" : "BOOLEAN";
            case "double" -> "DOUBLE";
            case "float" -> "REAL";
            default -> "VARCHAR(255)";
        };
    }

    private static String pkDdl(String dialect) {
        return switch (dialect) {
            case "mysql" -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
            case "sqlite" -> "INTEGER PRIMARY KEY AUTOINCREMENT";
            default -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
        };
    }

    private static String q(String ident, String dialect) {
        if ("mysql".equals(dialect)) {
            return "`" + ident + "`";
        }
        return "\"" + ident + "\"";
    }

    private static int pkIndex(List<OrmField> fields) {
        for (int i = 0; i < fields.size(); i++) {
            if (fields.get(i).generated()) return i;
        }
        return 0;
    }

    /** Linhas como JSON strings — mesmo shape do `KofJsDbBridge.query` untyped
     *  (colunas minúsculas na ordem de leitura, CLOB→String/BLOB→base64). */
    private static List<String> queryRows(String id, String sql, Object... binds) throws Exception {
        List<String> rows = new ArrayList<>();
        try (java.sql.PreparedStatement ps = KofJsDbBridge.conn(id).prepareStatement(sql)) {
            for (int i = 0; i < binds.length; i++) {
                ps.setObject(i + 1, binds[i]);
            }
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                java.sql.ResultSetMetaData md = rs.getMetaData();
                int cols = md.getColumnCount();
                while (rs.next()) {
                    Map<String, Object> row = new LinkedHashMap<>();
                    for (int i = 1; i <= cols; i++) {
                        row.put(md.getColumnLabel(i).toLowerCase(), norm(rs.getObject(i)));
                    }
                    rows.add(KofJsDbBridge.rowToJson(row));
                }
            }
        }
        return rows;
    }

    private static Object norm(Object v) throws Exception {
        if (v instanceof java.sql.Clob clob) {
            return clob.getSubString(1, (int) clob.length());
        }
        if (v instanceof java.sql.Blob blob) {
            return java.util.Base64.getEncoder().encodeToString(blob.getBytes(1, (int) blob.length()));
        }
        return v;
    }

    public static boolean create(String id, String table, String schemaStr) throws Exception {
        List<OrmField> fields = schema(schemaStr);
        String dialect = dialect(id);
        StringBuilder ddl = new StringBuilder("CREATE TABLE IF NOT EXISTS ")
                .append(q(table, dialect)).append(" (");
        for (int i = 0; i < fields.size(); i++) {
            if (i > 0) ddl.append(", ");
            OrmField f = fields.get(i);
            if (f.generated()) {
                ddl.append(q(f.name(), dialect)).append(' ').append(pkDdl(dialect));
            } else {
                ddl.append(q(f.name(), dialect)).append(' ').append(sqlType(f.type(), dialect));
                if (f.unique()) ddl.append(" UNIQUE");
            }
        }
        ddl.append(')');
        return KofJsDbBridge.execute(id, ddl.toString()) >= 0;
    }

    /** save — INSERT (sem PK, banco gera) / UPDATE (PK existente) / INSERT-upsert
     *  (PK inexistente). Retorna a linha salva como JSON string (com o PK gerado
     *  preenchido) p/ o guest fazer o bind via __kof_decode_<T>. */
    public static String save(String id, Value obj, String table, String schemaStr) throws Exception {
        return saveMap(id, KofJsDbBridge.valueMap(obj), table, schemaStr);
    }

    static String saveMap(String id, Map<String, Object> values, String table, String schemaStr) throws Exception {
        String dialect = dialect(id);
        List<OrmField> fields = schema(schemaStr);
        int pkIndex = pkIndex(fields);
        Object[] ordered = new Object[fields.size()];
        for (int i = 0; i < fields.size(); i++) {
            ordered[i] = values.get(fields.get(i).name());
        }
        Object pk = ordered[pkIndex];
        boolean pkIsNumeric = pk instanceof Number
                || "int".equals(fields.get(pkIndex).type())
                || "long".equals(fields.get(pkIndex).type());
        long pkLong = pk instanceof Number n ? n.longValue() : 0L;
        if (pk == null || (pkIsNumeric && pkLong == 0L)) {
            StringBuilder cols = new StringBuilder();
            StringBuilder marks = new StringBuilder();
            List<Object> binds = new ArrayList<>();
            for (int i = 0; i < fields.size(); i++) {
                if (i == pkIndex) continue;
                if (cols.length() > 0) { cols.append(", "); marks.append(", "); }
                cols.append(q(fields.get(i).name(), dialect));
                marks.append('?');
                binds.add(ordered[i]);
            }
            try (java.sql.PreparedStatement ps = KofJsDbBridge.conn(id).prepareStatement(
                    "INSERT INTO " + q(table, dialect) + " (" + cols + ") VALUES (" + marks + ")",
                    java.sql.Statement.RETURN_GENERATED_KEYS)) {
                for (int i = 0; i < binds.size(); i++) ps.setObject(i + 1, binds.get(i));
                ps.executeUpdate();
                try (java.sql.ResultSet keys = ps.getGeneratedKeys()) {
                    if (keys.next()) {
                        ordered[pkIndex] = norm(keys.getObject(1));
                    }
                }
            }
            return rowJson(fields, ordered);
        }
        StringBuilder sets = new StringBuilder();
        List<Object> binds = new ArrayList<>();
        for (int i = 0; i < fields.size(); i++) {
            if (i == pkIndex) continue;
            if (sets.length() > 0) sets.append(", ");
            sets.append(q(fields.get(i).name(), dialect)).append(" = ?");
            binds.add(ordered[i]);
        }
        binds.add(pk);
        try (java.sql.PreparedStatement ps = KofJsDbBridge.conn(id).prepareStatement(
                "UPDATE " + q(table, dialect) + " SET " + sets + " WHERE "
                        + q(fields.get(pkIndex).name(), dialect) + " = ?")) {
            for (int i = 0; i < binds.size(); i++) ps.setObject(i + 1, binds.get(i));
            if (ps.executeUpdate() > 0) {
                return rowJson(fields, ordered);
            }
        }
        StringBuilder cols = new StringBuilder();
        StringBuilder marks = new StringBuilder();
        List<Object> insertBinds = new ArrayList<>();
        for (int i = 0; i < fields.size(); i++) {
            if (cols.length() > 0) { cols.append(", "); marks.append(", "); }
            cols.append(q(fields.get(i).name(), dialect));
            marks.append('?');
            insertBinds.add(ordered[i]);
        }
        try (java.sql.PreparedStatement ps = KofJsDbBridge.conn(id).prepareStatement(
                "INSERT INTO " + q(table, dialect) + " (" + cols + ") VALUES (" + marks + ")")) {
            for (int i = 0; i < insertBinds.size(); i++) ps.setObject(i + 1, insertBinds.get(i));
            ps.executeUpdate();
        }
        return rowJson(fields, ordered);
    }

    private static String rowJson(List<OrmField> fields, Object[] values) {
        Map<String, Object> row = new LinkedHashMap<>();
        for (int i = 0; i < fields.size(); i++) {
            row.put(fields.get(i).name(), values[i]);
        }
        return KofJsDbBridge.rowToJson(row);
    }

    public static String find(String id, Object key, String table, String schemaStr) throws Exception {
        String dialect = dialect(id);
        List<OrmField> fields = schema(schemaStr);
        String pk = fields.get(pkIndex(fields)).name();
        List<String> rows = queryRows(id,
                "SELECT * FROM " + q(table, dialect) + " WHERE " + q(pk, dialect) + " = ?", key);
        return rows.isEmpty() ? null : rows.get(0);
    }

    public static List<String> all(String id, String table, String schemaStr) throws Exception {
        String dialect = dialect(id);
        return queryRows(id, "SELECT * FROM " + q(table, dialect));
    }

    public static List<String> where(String id, String field, Object value, String table,
            String schemaStr) throws Exception {
        String dialect = dialect(id);
        return queryRows(id, "SELECT * FROM " + q(table, dialect) + " WHERE "
                + q(field, dialect) + " = ?", value);
    }

    public static long count(String id, String table, String schemaStr) throws Exception {
        String dialect = dialect(id);
        try (java.sql.PreparedStatement ps = KofJsDbBridge.conn(id).prepareStatement(
                "SELECT COUNT(*) FROM " + q(table, dialect))) {
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getLong(1) : 0L;
            }
        }
    }

    public static long countWhere(String id, String field, Object value, String table,
            String schemaStr) throws Exception {
        String dialect = dialect(id);
        try (java.sql.PreparedStatement ps = KofJsDbBridge.conn(id).prepareStatement(
                "SELECT COUNT(*) FROM " + q(table, dialect) + " WHERE " + q(field, dialect) + " = ?")) {
            ps.setObject(1, value);
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getLong(1) : 0L;
            }
        }
    }

    public static boolean delete(String id, Object key, String table, String schemaStr) throws Exception {
        String dialect = dialect(id);
        List<OrmField> fields = schema(schemaStr);
        String pk = fields.get(pkIndex(fields)).name();
        return KofJsDbBridge.execute(id,
                "DELETE FROM " + q(table, dialect) + " WHERE " + q(pk, dialect) + " = ?", key) >= 0;
    }

    public static boolean deleteAll(String id, String table, String schemaStr) throws Exception {
        String dialect = dialect(id);
        return KofJsDbBridge.execute(id, "DELETE FROM " + q(table, dialect)) >= 0;
    }

    public static List<String> whereOp(String id, String field, String op, Object value,
            String table, String schemaStr) throws Exception {
        String dialect = dialect(id);
        String sqlOp = switch (op) {
            case ">", "<", ">=", "<=", "!=", "LIKE" -> op;
            case "==" -> "=";
            default -> throw new IllegalArgumentException("ORM operator not allowed: " + op);
        };
        return queryRows(id, "SELECT * FROM " + q(table, dialect) + " WHERE "
                + q(field, dialect) + " " + sqlOp + " ?", value);
    }

    public static List<String> page(String id, Object limit, Object offset, String table,
            String schemaStr) throws Exception {
        String dialect = dialect(id);
        int lim = ((Number) limit).intValue();
        int off = ((Number) offset).intValue();
        return queryRows(id, "SELECT * FROM " + q(table, dialect) + " LIMIT ? OFFSET ?", lim, off);
    }

    public static boolean migrate(String id, String name, String sql) throws Exception {
        String dialect = dialect(id);
        KofJsDbBridge.execute(id, "CREATE TABLE IF NOT EXISTS " + q("kof_migrations", dialect) + " ("
                + q("name", dialect) + " VARCHAR(255) PRIMARY KEY, "
                + q("applied_at", dialect) + " BIGINT)");
        try (java.sql.PreparedStatement ps = KofJsDbBridge.conn(id).prepareStatement(
                "SELECT COUNT(*) FROM " + q("kof_migrations", dialect) + " WHERE "
                        + q("name", dialect) + " = ?")) {
            ps.setString(1, name);
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                if (rs.next() && rs.getLong(1) > 0) {
                    return true;
                }
            }
        }
        if (KofJsDbBridge.execute(id, sql) < 0) {
            return false;
        }
        try (java.sql.PreparedStatement ps = KofJsDbBridge.conn(id).prepareStatement(
                "INSERT INTO " + q("kof_migrations", dialect) + " (" + q("name", dialect) + ", "
                        + q("applied_at", dialect) + ") VALUES (?, ?)")) {
            ps.setString(1, name);
            ps.setLong(2, System.currentTimeMillis());
            ps.executeUpdate();
        }
        return true;
    }

    public static boolean saveAll(String id, List<Map<String, Object>> items, String table,
            String schemaStr) throws Exception {
        for (Map<String, Object> item : items) {
            saveMap(id, item, table, schemaStr);
        }
        return true;
    }
}
